### ISSUE TITLE
Circuit breaker

### ISSUE THREAD

**Issue by threez** [pace/bricks#36]
First class circuit breaker support in go-microservice using

* https://github.com/Netflix-Skunkworks/hystrix-dashboard/wiki
* https://github.com/afex/hystrix-go

### Tasks

* [ ] concept
* [ ] devops dashboard & integration
* [ ] common stats endpoint for hystix
* [ ] prometheus metrics (e.g. number of open/close CB)
