### ISSUE TITLE
Allow more options to be set on Postgres connection pools

### ISSUE THREAD

**Issue by threez** [pace/bricks#45]
https://lab.jamit.de/pace/web/service/poi/merge_requests/140/diffs adds a new option to the Postgres connections: pool size.
That option should be part of the go microservice.

### Tasks

* [ ] port connection pool
* [ ] update wiki https://lab.jamit.de/pace/web/meta/wikis/concept/microservice
* [ ] consider adding other values to be configurable
