### ISSUE TITLE
Support testing in live

### ISSUE THREAD

**Issue by threez** [pace/bricks#47]
To assure the function of the service in a certain environment, a package with supportive functions should be created.

### Tasks

* [x] Should look similar to tests and therefore has to implement testing.TB
  * such that libraries like testify/assert can be used
  * tests could be executed in an integration test scenario as well
* [x] Test logging should end up in the log package
* [x] Test results are exposed via Prometheus
* [ ] ~~Filtering of tests is possible~~
* [x] Tests are repeated in a given interval
