### ISSUE TITLE
Add health check helpers

### ISSUE THREAD

**Issue by threez** [pace/bricks#90]
### Problem

An application/service is likely not available if the supporting infra is unavailable.
An external monitor wants to now about this situation to be able to do alerting.
Be aware this is worst case monitoring, there should be other monitoring in place, that triggers before the worst case did happen.

### Solution

There should be helpers inside pb to construct such an health endpoint easily

### Tasks

* [x] Checker for Postgres (RW)
* [ ] Checker for FileSystem (RW)
* [x] Checker for Redis (RW)
